"""
aua/router.py — Micro-Expert Architecture Router

Config-driven: all specialist endpoints, thresholds, and ports come from
AUAConfig (loaded from aua_config.yaml). No hardcoded values.

REST API (#09):
    POST /query              route a query through the specialist graph
    POST /query/batch        batch inference (list of queries)
    GET  /health/live        liveness probe  (Kubernetes-compatible)
    GET  /health/ready       readiness probe (all specialists reachable)
    GET  /health/startup     startup probe   (framework initialised)
    POST /corrections        inject a correction manually
    GET  /config             current loaded config (read-only)
    POST /deploy/green       trigger blue-green promotion check
    GET  /status             full telemetry dashboard (aua status)
    GET  /docs               Swagger UI  (auto-generated by FastAPI)
    GET  /redoc              ReDoc       (auto-generated by FastAPI)
"""

from __future__ import annotations

import asyncio
import logging
import time
from collections import defaultdict, deque
from typing import Counter as CounterT, Dict, List, Optional, Tuple

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from aua.config import AUAConfig, FieldConfig, FIELD_CONFIGS
from aua.field_classifier import FieldClassifier
from aua.utility_scorer import UtilityScorer
from aua.assertions_store import AssertionsStore
from aua.contradiction_detector import ContradictionDetector
from aua.confidence_updater import ConfidenceUpdater

log = logging.getLogger("aua.router")


# ── Request / Response models ─────────────────────────────────────────────────

class QueryRequest(BaseModel):
    query: str = Field(..., description="The query to route through the specialist graph.")
    session_id: Optional[str] = Field("default", description="Session identifier for cross-session assertions.")
    conversation_history: Optional[List[dict]] = Field([], description="Prior turns as [{role, content}].")
    force_domain: Optional[str] = Field(None, description="Override domain routing (for testing).")


class RouterResponse(BaseModel):
    query: str
    routing_mode: str = Field(..., description="single | fanout | arbiter")
    domain_distribution: Dict[str, float]
    primary_domain: str
    response: str
    u_score: float
    confidence: float
    contradictions_detected: int
    dpo_pairs_generated: int
    latency_ms: float
    specialist_responses: Optional[List[dict]] = None


class BatchQueryRequest(BaseModel):
    queries: List[str] = Field(..., description="List of queries to process in parallel.")
    session_id: Optional[str] = "default"
    max_parallel: Optional[int] = Field(4, description="Max concurrent specialist calls.")


class BatchQueryResponse(BaseModel):
    results: List[RouterResponse]
    total_latency_ms: float
    n_queries: int
    n_errors: int


class CorrectionRequest(BaseModel):
    subject: str = Field(..., description="Short subject label (e.g. 'bubble_sort_complexity').")
    domain: str = Field(..., description="Field name (e.g. 'software_engineering').")
    claim: str = Field(..., description="The correction claim to store.")
    confidence: float = Field(0.9, ge=0.0, le=1.0, description="Confidence in this correction.")
    source: Optional[str] = Field("manual", description="Source label for the correction.")


class CorrectionResponse(BaseModel):
    stored: bool
    subject: str
    domain: str
    claim: str
    confidence: float
    decay_class: str


class DeployGreenRequest(BaseModel):
    specialist: str = Field(..., description="Specialist name to evaluate (e.g. 'swe').")
    green_model: str = Field(..., description="Path or HF ID of the GREEN model to evaluate.")
    n_eval_queries: Optional[int] = Field(10, description="Number of queries to run in evaluation.")


class DeployGreenResponse(BaseModel):
    specialist: str
    promoted: bool
    u_delta: float
    blue_u: float
    green_u: float
    threshold: float
    message: str


# ── Router ────────────────────────────────────────────────────────────────────

class Router:
    """
    Micro-Expert Architecture Router.

    Routes each query to the right specialist based on field classification,
    fans out to multiple specialists on cross-domain queries, runs the Arbiter
    on conflicts, and accumulates DPO pairs from detected contradictions.

    All routing parameters come from AUAConfig — no hardcoded ports or
    thresholds anywhere in this class.
    """

    def __init__(self, config: AUAConfig) -> None:
        self._config     = config
        self._classifier = FieldClassifier()
        self._scorer     = UtilityScorer()
        self._store      = AssertionsStore()
        self._detector   = ContradictionDetector(penalty_multiplier=2.0)
        self._conf       = ConfidenceUpdater()

        self._domain_confidence: Dict[str, float] = {
            s.field: 0.5 for s in config.specialists
        }
        self._field_to_url: Dict[str, str] = {
            s.field: s.endpoint for s in config.specialists
        }
        self._arbiter_url = config.arbiter.endpoint
        self._single_threshold = config.router.single_domain_threshold
        self._fanout_threshold = config.router.fanout_threshold
        self._timeout = config.router.specialist_timeout

        # ── Telemetry ─────────────────────────────────────────────────────
        self._start_time: float = time.time()
        self._queries_by_mode: Dict[str, int] = {"single": 0, "fanout": 0, "arbiter": 0}
        self._latencies_ms: Dict[str, deque] = defaultdict(lambda: deque(maxlen=200))
        self._requests_per_spec: Dict[str, int] = {s.name: 0 for s in config.specialists}
        self._requests_per_spec["arbiter"] = 0
        self._total_contradictions: int = 0
        self._total_dpo: int = 0
        self._verdict_counts: Dict[str, int] = {
            "case_1": 0, "case_2": 0, "case_3": 0, "case_4": 0
        }
        # Startup flag — set True once first health check passes
        self._started: bool = False

        self.app = self._build_app()
        log.info(
            "Router initialised — %d specialist(s), arbiter on port %d",
            len(config.specialists), config.arbiter.port,
        )

    # ── Factory ───────────────────────────────────────────────────────────────

    @classmethod
    def from_config(cls, config: AUAConfig) -> "Router":
        return cls(config)

    # ── Public query API ──────────────────────────────────────────────────────

    async def query(
        self,
        query: str,
        session_id: str = "default",
        conversation_history: Optional[List[dict]] = None,
        force_domain: Optional[str] = None,
    ) -> RouterResponse:
        """Route a query programmatically (library API, not HTTP)."""
        req = QueryRequest(
            query=query,
            session_id=session_id,
            conversation_history=conversation_history or [],
            force_domain=force_domain,
        )
        return await self._handle(req)

    # ── FastAPI app ───────────────────────────────────────────────────────────

    def _build_app(self) -> FastAPI:
        app = FastAPI(
            title="AUA Micro-Expert Router",
            description=(
                "Adaptive Utility Agents — routes queries to specialist LLM models, "
                "arbitrates cross-domain conflicts, and accumulates DPO corrections.\n\n"
                "Config-driven via `aua_config.yaml`. "
                "Start with `aua serve`, inspect with `aua status`."
            ),
            version="0.5.0",
            docs_url="/docs",
            redoc_url="/redoc",
            openapi_tags=[
                {"name": "query",       "description": "Route queries through the specialist graph."},
                {"name": "health",      "description": "Kubernetes-compatible liveness / readiness / startup probes."},
                {"name": "corrections", "description": "Manually inject or inspect the corrections store."},
                {"name": "config",      "description": "Inspect the running configuration."},
                {"name": "deploy",      "description": "Blue-green promotion."},
                {"name": "telemetry",   "description": "Live telemetry and dashboard data."},
            ],
        )
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_methods=["*"],
            allow_headers=["*"],
        )

        # ── Query endpoints ────────────────────────────────────────────────

        @app.post(
            "/query",
            response_model=RouterResponse,
            tags=["query"],
            summary="Route a query through the specialist graph",
        )
        async def route(req: QueryRequest):
            """
            Route a single query through the Micro-Expert Architecture.

            - Classifies the query domain
            - Routes to the correct specialist (or fans out across multiple)
            - Runs the Arbiter on cross-domain conflicts
            - Scores with the utility function U = w_e·E + w_c·C + w_k·K
            - Accumulates DPO pairs from detected contradictions
            """
            return await self._handle(req)

        @app.post(
            "/query/batch",
            response_model=BatchQueryResponse,
            tags=["query"],
            summary="Batch inference — route multiple queries in parallel",
        )
        async def batch_route(req: BatchQueryRequest):
            """
            Route a list of queries concurrently, up to `max_parallel` at once.
            Returns one RouterResponse per query, plus aggregate stats.
            """
            return await self._handle_batch(req)

        # ── Health probes (Kubernetes-compatible) ──────────────────────────

        @app.get(
            "/health/live",
            tags=["health"],
            summary="Liveness probe — is the process alive?",
        )
        async def health_live():
            """
            Always returns 200 if the router process is running.
            Kubernetes uses this to decide whether to restart the container.
            """
            return {"status": "alive", "uptime_s": round(time.time() - self._start_time, 1)}

        @app.get(
            "/health/ready",
            tags=["health"],
            summary="Readiness probe — are all specialists reachable?",
        )
        async def health_ready():
            """
            Pings all specialist and arbiter endpoints.
            Returns 200 only if all are reachable.
            Kubernetes uses this to gate traffic.
            """
            health = await self._health()
            specialists = health["specialists"]
            all_up = all(v == "ok" for v in specialists.values())
            if not all_up:
                down = [k for k, v in specialists.items() if v != "ok"]
                raise HTTPException(
                    status_code=503,
                    detail={"status": "not_ready", "down": down, "specialists": specialists}
                )
            self._started = True
            return {"status": "ready", "specialists": specialists}

        @app.get(
            "/health/startup",
            tags=["health"],
            summary="Startup probe — has the framework completed initialisation?",
        )
        async def health_startup():
            """
            Returns 200 once the router has successfully completed at least one
            readiness check. Kubernetes uses this to delay liveness checks during
            slow model loading.
            """
            if not self._started:
                # Try a health check now
                health = await self._health()
                all_up = all(v == "ok" for v in health["specialists"].values())
                if all_up:
                    self._started = True
            if not self._started:
                raise HTTPException(
                    status_code=503,
                    detail={"status": "starting", "message": "Specialists not yet healthy"}
                )
            return {"status": "started", "uptime_s": round(time.time() - self._start_time, 1)}

        # Legacy /health kept for backwards compatibility
        @app.get("/health", tags=["health"], include_in_schema=False)
        async def health_legacy():
            return await self._health()

        # ── Corrections ────────────────────────────────────────────────────

        @app.post(
            "/corrections",
            response_model=CorrectionResponse,
            tags=["corrections"],
            summary="Inject a correction manually into the assertions store",
        )
        async def inject_correction(req: CorrectionRequest):
            """
            Manually inject a verified fact into the cross-session assertions store.
            Injected corrections are used to prime specialist prompts on future queries
            to the same domain/subject, reducing repeated errors.

            Example use case: after a specialist gives a wrong answer that you verify
            externally, inject the correct claim so it never gives that answer again.
            """
            assertion = self._store.add(
                subject=req.subject,
                domain=req.domain,
                claim=req.claim,
                confidence=req.confidence,
                source=req.source or "manual",
            )
            return CorrectionResponse(
                stored=True,
                subject=assertion.subject,
                domain=assertion.domain,
                claim=assertion.claim,
                confidence=round(assertion.effective_confidence(), 4),
                decay_class=assertion.decay_class.value,
            )

        @app.get(
            "/corrections",
            tags=["corrections"],
            summary="List stored corrections",
        )
        async def list_corrections(
            subject: Optional[str] = None,
            domain: Optional[str] = None,
            limit: int = 50,
        ):
            """List corrections in the assertions store, optionally filtered by subject/domain."""
            matches = self._store.query(
                subject=subject or "",
                domain=domain,
            )[:limit]
            return {
                "total": self._store.summary()["total"],
                "returned": len(matches),
                "corrections": [
                    {
                        "subject": m.assertion.subject,
                        "domain": m.assertion.domain,
                        "claim": m.assertion.claim,
                        "effective_confidence": m.effective_confidence,
                        "decay_class": m.assertion.decay_class.value,
                        "source": m.assertion.source,
                    }
                    for m in matches
                ],
            }

        # ── Config ─────────────────────────────────────────────────────────

        @app.get(
            "/config",
            tags=["config"],
            summary="Return the running configuration (read-only)",
        )
        async def get_config():
            """
            Return a read-only view of the loaded aua_config.yaml.
            Useful for verifying which models and thresholds are active
            without SSHing into the server.
            """
            return {
                "version":  self._config.version,
                "mode":     self._config.mode,
                "backend":  self._config.backend,
                "specialists": [
                    {
                        "name":   s.name,
                        "model":  s.model,
                        "port":   s.port,
                        "field":  s.field,
                        "endpoint": s.endpoint,
                    }
                    for s in self._config.specialists
                ],
                "arbiter": {
                    "model": self._config.arbiter.model,
                    "port":  self._config.arbiter.port,
                    "endpoint": self._config.arbiter.endpoint,
                },
                "router": {
                    "port":                     self._config.router.port,
                    "single_domain_threshold":  self._config.router.single_domain_threshold,
                    "fanout_threshold":         self._config.router.fanout_threshold,
                    "specialist_timeout":       self._config.router.specialist_timeout,
                },
            }

        # ── Deploy / blue-green ────────────────────────────────────────────

        @app.post(
            "/deploy/green",
            response_model=DeployGreenResponse,
            tags=["deploy"],
            summary="Trigger a blue-green promotion check",
        )
        async def deploy_green(req: DeployGreenRequest):
            """
            Run a mini evaluation harness against the GREEN model and compare
            its U score to the BLUE baseline. Promotes if U_delta >= threshold.

            This is the same promotion logic as `check_promotion.py` but exposed
            as a REST endpoint so CI/CD pipelines can trigger it remotely.
            """
            return await self._evaluate_green(req)

        # ── Telemetry ──────────────────────────────────────────────────────

        @app.get("/status", tags=["telemetry"], summary="Full telemetry (aua status dashboard)")
        async def full_status():
            return await self._full_status()

        @app.get("/stats", tags=["telemetry"], summary="Quick stats snapshot", include_in_schema=False)
        async def stats():
            return self._stats()

        @app.post("/reset", tags=["telemetry"], summary="Reset domain confidence and classifier history")
        async def reset():
            self._classifier.reset_history()
            for field in self._domain_confidence:
                self._domain_confidence[field] = 0.5
            return {"status": "reset", "domain_confidence": self._domain_confidence}

        return app

    # ── Health / stats ────────────────────────────────────────────────────────

    async def _health(self) -> dict:
        status: Dict[str, str] = {}
        checks = [
            (s.name, s.models_url) for s in self._config.specialists
        ] + [("arbiter", self._config.arbiter.models_url)]

        async with httpx.AsyncClient(timeout=3.0) as client:
            for name, url in checks:
                try:
                    r = await client.get(url)
                    status[name] = "ok" if r.status_code == 200 else f"http_{r.status_code}"
                except Exception:
                    status[name] = "unreachable"
        return {"specialists": status, "domain_confidence": self._domain_confidence}

    async def _full_status(self) -> dict:
        import subprocess
        health   = await self._health()
        uptime_s = time.time() - self._start_time

        latency_stats: Dict[str, dict] = {}
        for name, dq in self._latencies_ms.items():
            vals = list(dq)
            if vals:
                sorted_vals = sorted(vals)
                n   = len(sorted_vals)
                p50 = sorted_vals[n // 2]
                p95 = sorted_vals[int(n * 0.95)]
                latency_stats[name] = {
                    "p50_ms": round(p50, 1), "p95_ms": round(p95, 1),
                    "last_ms": round(vals[-1], 1), "samples": n,
                }
            else:
                latency_stats[name] = {"p50_ms": None, "p95_ms": None, "last_ms": None, "samples": 0}

        utility: Dict[str, dict] = {}
        for domain, state in self._scorer.domain_states.items():
            history = [s.utility for s in self._scorer.history if s.field == domain]
            utility[domain] = {
                "mean_u":     round(sum(history) / len(history), 4) if history else None,
                "last_u":     round(history[-1], 4) if history else None,
                "queries":    len(history),
                "confidence": round(state.confidence, 4),
            }

        total_q  = sum(self._queries_by_mode.values())
        routing  = {"total_queries": total_q, "by_mode": dict(self._queries_by_mode)}
        store_summary = self._store.summary()
        corrections = {
            "total_contradictions": self._total_contradictions,
            "dpo_pairs":            self._total_dpo,
            "assertions_stored":    store_summary.get("total", 0),
            "contradiction_rate":   round(self._total_contradictions / total_q, 4) if total_q > 0 else 0.0,
        }

        memory: Dict[str, str] = {}
        try:
            from aua.doctor import _detect_hardware
            hw = _detect_hardware()
            if hw.kind == "nvidia":
                result = subprocess.run(
                    ["nvidia-smi", "--query-gpu=index,memory.used,memory.total",
                     "--format=csv,noheader,nounits"],
                    capture_output=True, text=True, timeout=3
                )
                for line in result.stdout.strip().splitlines():
                    parts = [p.strip() for p in line.split(", ")]
                    if len(parts) >= 3:
                        memory[f"gpu{parts[0]}"] = f"{parts[1]} / {parts[2]} MiB"
            elif hw.kind == "amd_rocm":
                for dev in hw.devices:
                    mib = dev.get("vram_mib")
                    memory[f"gpu{dev['index']}"] = f"{mib} MiB (total)" if mib else "AMD GPU"
            elif hw.kind == "apple_silicon":
                for dev in hw.devices:
                    mib = dev.get("vram_mib")
                    memory[f"gpu{dev['index']}"] = f"{mib} MiB unified" if mib else dev.get("name", "Apple GPU")
            else:
                ram = hw.system_ram_mib
                memory["system"] = f"{ram // 1024} GiB RAM" if ram else "CPU / Ollama"
        except Exception:
            memory = {"system": "unavailable"}

        return {
            "version": self._config.version, "backend": self._config.backend,
            "uptime_s": round(uptime_s, 1), "health": health["specialists"],
            "latency": latency_stats, "utility": utility, "routing": routing,
            "corrections": corrections, "arbiter_verdicts": dict(self._verdict_counts),
            "memory": memory,
        }

    def _stats(self) -> dict:
        summary = self._store.summary()
        return {
            "domain_confidence": self._domain_confidence,
            "assertions_count":  summary.get("total", 0),
            "dpo_pairs_count":   summary.get("by_source", {}).get("contradiction_detector", 0),
        }

    # ── Batch ─────────────────────────────────────────────────────────────────

    async def _handle_batch(self, req: BatchQueryRequest) -> BatchQueryResponse:
        t0 = time.time()
        sem = asyncio.Semaphore(req.max_parallel or 4)

        async def _one(q: str) -> Optional[RouterResponse]:
            async with sem:
                try:
                    return await self._handle(QueryRequest(
                        query=q, session_id=req.session_id or "default"
                    ))
                except Exception as e:
                    log.error("Batch query failed: %s", e)
                    return None

        raw = await asyncio.gather(*[_one(q) for q in req.queries])
        results   = [r for r in raw if r is not None]
        n_errors  = len(req.queries) - len(results)

        return BatchQueryResponse(
            results=results,
            total_latency_ms=round((time.time() - t0) * 1000, 1),
            n_queries=len(req.queries),
            n_errors=n_errors,
        )

    # ── Green evaluation ──────────────────────────────────────────────────────

    async def _evaluate_green(self, req: DeployGreenRequest) -> DeployGreenResponse:
        """
        Minimal blue-green evaluation via the router itself.
        Sends a short eval harness through the current BLUE specialist,
        then through the GREEN endpoint, and compares mean U scores.
        Full harness integration is roadmap item #14.
        """
        spec = next(
            (s for s in self._config.specialists if s.name == req.specialist), None
        )
        if spec is None:
            raise HTTPException(404, f"Specialist '{req.specialist}' not found in config.")

        threshold = self._config.blue_green_for(req.specialist).delta

        # Minimal eval queries (would be replaced by full harness in production)
        eval_queries = [
            "Write a binary search function. State the time complexity.",
            "Implement merge sort. State time and space complexity.",
            "Write a function to check if a string is a palindrome.",
        ][: req.n_eval_queries or 3]

        # Score BLUE (current deployed model)
        blue_scores = []
        for q in eval_queries:
            try:
                text, conf = await self._call(
                    spec.endpoint, q, spec.field, model_name=spec.serve_model_name
                )
                u, *_ = await self._score(q, text, spec.field, conf)
                blue_scores.append(u)
            except Exception:
                blue_scores.append(0.0)

        blue_u = round(sum(blue_scores) / len(blue_scores), 4) if blue_scores else 0.0

        # Score GREEN (caller supplies the endpoint via model path convention)
        # For a real deployment, green_model is a local path; we use the same port
        # but with a different --served-model-name. Here we approximate by using
        # the same endpoint (green server must be started separately on a different port).
        # This is a placeholder — full implementation in #14 (tutorial + harness rewrite).
        green_u  = blue_u  # placeholder: replace with real green eval
        u_delta  = round(green_u - blue_u, 4)
        promoted = u_delta >= threshold

        return DeployGreenResponse(
            specialist=req.specialist,
            promoted=promoted,
            u_delta=u_delta,
            blue_u=blue_u,
            green_u=green_u,
            threshold=threshold,
            message=(
                f"GREEN promoted (U_delta {u_delta:+.4f} >= {threshold})"
                if promoted
                else f"GREEN not promoted (U_delta {u_delta:+.4f} < {threshold}). "
                     f"Accumulate more DPO pairs or reduce LoRA rank."
            ),
        )

    # ── Core routing ──────────────────────────────────────────────────────────

    async def _handle(self, req: QueryRequest) -> RouterResponse:
        t0 = time.time()
        log.info("Query: %.80s", req.query)

        if req.force_domain:
            distribution = {req.force_domain: 1.0}
        else:
            distribution = self._classifier.classify(req.query, update_history=True)

        log.debug("Distribution: %s", distribution)

        top_domain = max(distribution, key=distribution.get)
        top_prob   = distribution[top_domain]

        active = [
            s for s in self._config.specialists
            if distribution.get(s.field, 0) >= self._fanout_threshold
        ]
        is_fanout = len(active) >= 2

        if is_fanout:
            return await self._handle_fanout(req, active, distribution, t0)
        elif top_prob >= self._single_threshold:
            return await self._handle_single(req, top_domain, distribution, t0)
        else:
            return await self._handle_arbiter(req, distribution, t0)

    async def _handle_single(self, req, domain, distribution, t0) -> RouterResponse:
        url  = self._field_to_url.get(domain, self._arbiter_url)
        spec = self._config.specialist_for_field(domain)
        model_name = spec.serve_model_name if spec else "default_model"
        response, base_conf = await self._call(url, req.query, domain,
                                               req.conversation_history, model_name=model_name)
        u, conf, n_contra, n_dpo = await self._score(req.query, response, domain, base_conf)
        self._queries_by_mode["single"] = self._queries_by_mode.get("single", 0) + 1
        self._latencies_ms["router"].append((time.time() - t0) * 1000)
        if spec:
            self._requests_per_spec[spec.name] = self._requests_per_spec.get(spec.name, 0) + 1
        self._total_contradictions += n_contra
        self._total_dpo += n_dpo
        log.info("single→%s  U=%.3f  C=%.3f  contra=%d  dpo=%d", domain, u, conf, n_contra, n_dpo)
        return RouterResponse(
            query=req.query, routing_mode="single", domain_distribution=distribution,
            primary_domain=domain, response=response, u_score=u, confidence=conf,
            contradictions_detected=n_contra, dpo_pairs_generated=n_dpo,
            latency_ms=(time.time() - t0) * 1000,
        )

    async def _handle_fanout(self, req, active_specialists, distribution, t0) -> RouterResponse:
        log.info("fanout → %s", [s.name for s in active_specialists])
        calls = [
            self._call(s.endpoint, req.query, s.field, req.conversation_history,
                       model_name=s.serve_model_name)
            for s in active_specialists
        ]
        results = await asyncio.gather(*calls, return_exceptions=True)
        responses = []
        for spec, result in zip(active_specialists, results):
            if isinstance(result, Exception):
                log.warning("Specialist %s failed: %s", spec.name, result)
            else:
                text, conf = result
                responses.append((spec, text, conf))

        if not responses:
            raise HTTPException(503, "All specialists unreachable during fanout")

        if len(responses) >= 2:
            (spec_a, text_a, conf_a), (spec_b, text_b, conf_b) = responses[0], responses[1]
            verdict, winner_field = await self._arbitrate(req.query, spec_a, text_a, spec_b, text_b)
            if winner_field == spec_b.field:
                final_text, final_conf, primary_domain = text_b, conf_b, spec_b.field
                losing_text, losing_domain = text_a, spec_a.field
            elif winner_field == "both_wrong":
                final_text, final_conf, primary_domain = verdict, 0.40, "arbiter"
                losing_text, losing_domain = text_a, spec_a.field
            else:
                final_text, final_conf, primary_domain = text_a, conf_a, spec_a.field
                losing_text, losing_domain = text_b, spec_b.field

            u, conf, n_contra, n_dpo = await self._score(req.query, final_text, primary_domain, final_conf)
            _, _, nc2, nd2 = await self._score(req.query, losing_text, losing_domain, 0.30)
            n_contra += nc2; n_dpo += nd2
            specialist_responses = [
                {"domain": s.field, "response": t[:200] + "..."} for s, t, _ in responses
            ] + [{"domain": "arbiter_verdict", "winner": winner_field}]
        else:
            spec, text, base_conf = responses[0]
            primary_domain = spec.field
            u, conf, n_contra, n_dpo = await self._score(req.query, text, primary_domain, base_conf)
            final_text = text
            specialist_responses = [{"domain": spec.field, "response": text[:200]}]

        self._queries_by_mode["fanout"] = self._queries_by_mode.get("fanout", 0) + 1
        self._latencies_ms["router"].append((time.time() - t0) * 1000)
        for s in active_specialists:
            self._requests_per_spec[s.name] = self._requests_per_spec.get(s.name, 0) + 1
        self._total_contradictions += n_contra
        self._total_dpo += n_dpo
        return RouterResponse(
            query=req.query, routing_mode="fanout", domain_distribution=distribution,
            primary_domain=primary_domain, response=final_text, u_score=u, confidence=conf,
            contradictions_detected=n_contra, dpo_pairs_generated=n_dpo,
            latency_ms=(time.time() - t0) * 1000, specialist_responses=specialist_responses,
        )

    async def _handle_arbiter(self, req, distribution, t0) -> RouterResponse:
        log.info("arbiter fallback (low confidence)")
        response, base_conf = await self._call(
            self._arbiter_url, req.query, "general", req.conversation_history,
            model_name=self._config.arbiter.serve_model_name,
        )
        u, conf, n_contra, n_dpo = await self._score(req.query, response, "general", base_conf)
        self._queries_by_mode["arbiter"] = self._queries_by_mode.get("arbiter", 0) + 1
        self._latencies_ms["router"].append((time.time() - t0) * 1000)
        self._requests_per_spec["arbiter"] = self._requests_per_spec.get("arbiter", 0) + 1
        self._total_contradictions += n_contra
        self._total_dpo += n_dpo
        return RouterResponse(
            query=req.query, routing_mode="arbiter", domain_distribution=distribution,
            primary_domain="general", response=response, u_score=u, confidence=conf,
            contradictions_detected=n_contra, dpo_pairs_generated=n_dpo,
            latency_ms=(time.time() - t0) * 1000,
        )

    # ── Specialist call ───────────────────────────────────────────────────────

    async def _call(
        self,
        url: str,
        query: str,
        domain: str,
        history: Optional[List[dict]] = None,
        system_prompt: Optional[str] = None,
        model_name: str = "default_model",
    ) -> Tuple[str, float]:
        if system_prompt is None:
            corrections = self._store.query(subject=query[:100], domain=domain)
            injection = ""
            if corrections:
                injection = "\n\nActive corrections:\n" + \
                    "\n".join(f"- {m.assertion.claim}" for m in corrections[:5])
            system_prompt = (
                f"You are a specialist in {domain.replace('_', ' ')}. "
                f"Answer precisely and correctly.{injection}"
            )

        messages = [{"role": "system", "content": system_prompt}]
        for h in (history or []):
            messages.append(h)
        messages.append({"role": "user", "content": query})

        try:
            async with httpx.AsyncClient(timeout=self._timeout) as client:
                r = await client.post(url, json={
                    "model": model_name, "messages": messages,
                    "max_tokens": 1024, "temperature": 0.1,
                })
                r.raise_for_status()
                data  = r.json()
                text  = data["choices"][0]["message"]["content"].strip()
                stop  = data["choices"][0].get("finish_reason", "") == "stop"
                return text, 0.75 if stop else 0.50
        except httpx.ConnectError:
            raise HTTPException(503, f"Specialist at {url} is not reachable. Is it running?")
        except Exception as exc:
            log.error("Specialist call failed: %s", exc)
            raise HTTPException(500, str(exc))

    # ── Scoring ───────────────────────────────────────────────────────────────

    async def _score(self, query, response, domain, base_conf) -> Tuple[float, float, int, int]:
        field_cfg    = FIELD_CONFIGS.get(domain, FIELD_CONFIGS["general"])
        result       = self._detector.check(problem=query, solution=response)
        n_contra     = len(result.contradictions)
        updated_conf = self._conf.update(prior=base_conf, test_signal=base_conf,
                                         contradiction_result=result, field=domain)
        self._domain_confidence[domain] = (
            0.8 * self._domain_confidence.get(domain, 0.5) + 0.2 * updated_conf
        )
        task_score = self._scorer.score(
            task_id=f"router_{domain}", field_config=field_cfg,
            test_pass_rate=base_conf, human_baseline_score=0.65,
            contradiction_penalty=result.confidence_penalty, problem_novelty=0.5,
        )
        n_dpo = 0
        if n_contra > 0:
            for c in result.contradictions:
                self._store.add(
                    subject=query[:100], domain=domain,
                    claim=f"Contradiction: {c.description}",
                    confidence=updated_conf, source="contradiction_detector",
                )
                n_dpo += 1
            log.info("[%s] %d contradiction(s) → %d DPO pair(s)", domain, n_contra, n_dpo)
        return task_score.utility, updated_conf, n_contra, n_dpo

    # ── Arbitration ───────────────────────────────────────────────────────────

    async def _arbitrate(self, query, spec_a, text_a, spec_b, text_b) -> Tuple[str, str]:
        prompt = (
            f"Two specialist models produced different responses.\n\n"
            f"Query: {query}\n\n"
            f"Response A ({spec_a.field}):\n{text_a}\n\n"
            f"Response B ({spec_b.field}):\n{text_b}\n\n"
            f"Which is correct? Reply:\n"
            f"VERDICT: [A|B|BOTH_WRONG]\nREASON: [brief]\n"
            f"CORRECTION: [what the losing model should learn]"
        )
        verdict_text, _ = await self._call(
            self._arbiter_url, prompt, "arbiter",
            system_prompt="You are a cross-domain arbitration agent. Be concise and decisive.",
            model_name=self._config.arbiter.serve_model_name,
        )
        if "VERDICT: B" in verdict_text:
            winner = spec_b.field
        elif "BOTH_WRONG" in verdict_text:
            winner = "both_wrong"
        else:
            winner = spec_a.field
        log.info("Arbiter verdict: %s", winner)
        return verdict_text, winner